import { useState } from 'react'
import type { ReactNode } from 'react'
import { AlertCircle, Check, ChevronLeft, ChevronRight, Loader2, X, ShieldCheck } from 'lucide-react'
import type { Severity } from '../types'
export const severityColors:Record<Severity,string>={critical:'#fb7185',high:'#fbbf65',medium:'#a78bfa',low:'#60a5fa',informational:'#8292a9'}
export function Badge({value}:{value:string}){return <span className={`badge badge-${value.toLowerCase().replaceAll(' ','-')}`}><i/>{value}</span>}
export function ErrorBox({message}:{message:string}){return message ? <div className="error-box" role="alert"><AlertCircle size={17}/>{message}</div> : null}
export function Loading(){return <div className="loading" role="status"><Loader2 className="spin" size={24}/>Loading security data…</div>}
export function Empty({title='No records found',text='Try adjusting your filters or ingest security events.'}:{title?:string;text?:string}){return <div className="empty"><ShieldCheck size={34}/><h3>{title}</h3><p>{text}</p></div>}
export function Panel({title,subtitle,action,children,className=''}:{title:string;subtitle?:string;action?:ReactNode;children:ReactNode;className?:string}){return <section className={`panel ${className}`}><div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>{children}</section>}
export function PageHeading({eyebrow='SECURITY OPERATIONS',title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="heading-actions">{action}</div></div>}
export function Pagination({page,total,pageSize,onChange}:{page:number;total:number;pageSize:number;onChange:(page:number)=>void}){return <div className="pagination"><span>{total?`${(page-1)*pageSize+1}–${Math.min(page*pageSize,total)}`:'0'} of {total} records</span><div><button aria-label="Previous page" disabled={page===1} onClick={()=>onChange(page-1)}><ChevronLeft size={16}/></button><span>Page {page}</span><button aria-label="Next page" disabled={page*pageSize>=total} onClick={()=>onChange(page+1)}><ChevronRight size={16}/></button></div></div>}
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop" onClick={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')onClose()}}><div className="panel-heading"><h2>{title}</h2><button autoFocus aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</section></div>}
export function ActionButton({children,action,onDone,className='button primary'}:{children:ReactNode;action:()=>Promise<unknown>;onDone?:()=>void;className?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);return <><button className={className} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await action();setDone(true);onDone?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?<Loader2 size={15} className="spin"/>:done?<Check size={15}/>:null}{children}</button><ErrorBox message={error}/></>}
export function formatDate(value:string){return new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
